repos: 
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: hatch-test
        name: hatch-test
        entry: hatch test -a
        language: system
        fail_fast: True
        pass_filenames: false
        always_run: true
      - id: sphinx
        name: docs-check
        entry: make docs
        language: system
        always_run: false 
        pass_filenames: false
