[run]
source = xenopict
branch = True
omit =
    # Version files
    xenopict/_version.py
    xenopict/_static_version.py
    # Difficult to test files
    xenopict/magic.py
    xenopict/monkey.py
    # Test files
    xenopict/tests/*
    # Setup files
    setup.py
    conf.py

[report]
exclude_lines =
    pragma: no cover
    def __repr__
    def __str__
    raise NotImplementedError
    if __name__ == .__main__.:
    pass
    raise ImportError
    except ImportError:
    def __getattr__
    @(abc\.)?abstractmethod
    TYPE_CHECKING
    if TYPE_CHECKING:
    \.\.\.

[xml]
output = coverage.xml

[json]
output = coverage.json
pretty_print = true 
